pipeline{
    agent any 
        stages{
            stage('checkout'){
                steps{

                }
            }
            stage('test'){
                steps{

                }

            }
            stage('code quality'){
                steps{

                }

            }
            stage(){
                steps{

                }

            }
        }
    
}